#!/usr/bin/env ruby

$LOAD_PATH.unshift File.expand_path(ENV['SOURCE_DIR'], __FILE__)

require 'context'
require 'api'

context = Context.new
output = []

API.init(context)
API.check do |versions|
  output = versions.map { |version| { "version" => version } }
end

STDOUT.puts output.to_json
