#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path(ENV['SOURCE_DIR'], __FILE__)

require 'context'
require 'api'

context = Context.new
output = {
  "version" => { "version" => context.version },
  "metadata" => []
}

API.init(context)
API.in do |monsters|
  output["metadata"] << { "name" => "count", "value" => monsters.size.to_s }
  context.write("monsters.csv", monsters.map { |m| m.join(",") }.join("\r\n"))
end

STDOUT.puts output.to_json
