#!/usr/bin/env ruby
$LOAD_PATH.unshift File.expand_path(ENV['SOURCE_DIR'], __FILE__)

require 'context'
require 'api'

context = Context.new
output = {
  "version" => {"version" => context.version },
  "metadata" => []
}

API.init(context)
API.out do |updated_at|
  output["metadata"] << { "name" => "updated_at", "value" => updated_at.strftime("%Y-%m-%d") }
end

STDOUT.puts output.to_json
